apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: com-bank-core-service-customercredittransferinitiation
spec:
   selector:
      matchLabels:
         app: com-bank-core-service-customercredittransferinitiation # a lable to match with other services(Objects eg: Service)
   replicas: 1 # tells deployment to run 2 pods matching the template
   template:
      metadata:
         labels:
            app: com-bank-core-service-customercredittransferinitiation
      spec:
         containers:
         -  name: com-bank-core-service-customercredittransferinitiation
            image: dsilvamarsh/com-bank-core-service-customercredittransferinitiation:1.0.0
            env: 
            - name: JAVA_OPTS
              value: "-Xmx200m -Xms150m" 
            resources:
               limits:
                  memory: 210Mi
               requests:
                  cpu: 100m
                  memory: 200Mi
            imagePullPolicy: Always
            ports:
            -  containerPort: 8081
         imagePullSecrets:
         -  name: dsilvamarsh
---
apiVersion: v1
kind: Service
metadata:
   name: com-bank-core-service-customercredittransferinitiation
spec:
   type: NodePort
   selector:
      app: com-bank-core-service-customercredittransferinitiation
   ports:
   -  protocol: TCP
      port: 8081
      name: http