apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgres
spec:
   selector:
      matchLabels:
         app: postgres
   replicas: 1
   template:
      metadata:
         labels:
            app: postgres
      spec:
         containers:
         -  name: postgres
            image: postgres:12.2
            imagePullPolicy: IfNotPresent
            envFrom:
            -  configMapRef:
                  name: postgres-config
            resources:
               limits:
                  cpu: 100m
                  memory: 200Mi
               requests:
                  cpu: 50m
                  memory: 100Mi
            volumeMounts:
            -  mountPath: /var/lib/postgresql/data
               name: postgredb
         volumes:
         -  name: postgredb
            persistentVolumeClaim:
               claimName: postgres-pv-claim
         imagePullSecrets:
         -  name: regcred
         restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
   name: postgres
   labels:
      app: postgres
spec:
   ports:
   -  name: postgres
      port: 5432
      nodePort: 30432
   type: NodePort
   selector:
      app: postgres